if LoadPackage("nq")<>true then FORCE_QUIT_GAP(1);fi;
a:=NilpotentQuotient(FreeGroup(2),3);;
b:=NilpotentQuotient(FreeGroup(2),2);;
g:=DirectProduct(a,b);;
ea:=Embedding(g,1);;eb:=Embedding(g,2);;
x:=Image(ea,GeneratorsOfGroup(a)[1]);;y:=Image(ea,GeneratorsOfGroup(a)[2]);;
u:=Image(eb,GeneratorsOfGroup(b)[1]);;v:=Image(eb,GeneratorsOfGroup(b)[2]);;
c:=Comm(x,y);;t:=Comm(u,v);;
h1:=Subgroup(g,[x,y,c*t]);;h2:=Subgroup(g,[u,v]);;
if not t in h1 or not t in h2 or Order(t)<>infinity then FORCE_QUIT_GAP(1);fi;
if not t in Centre(h1) or not t in Centre(h2) then FORCE_QUIT_GAP(1);fi;
z:=Centre(g);;proj:=NaturalHomomorphismByNormalSubgroup(g,z);;
q:=Image(proj,Image(ea));;
liftseq:=List([x,y,c*t],w->Image(proj,w));;
if Subgroup(Image(proj),liftseq)<>q then FORCE_QUIT_GAP(1);fi;
if HirschLength(q)<>3 or NilpotencyClassOfGroup(q)<>2 then FORCE_QUIT_GAP(1);fi;
Print("Quotient factor Hirsch length: ",HirschLength(q),"; class: ",NilpotencyClassOfGroup(q),"\n");
Print("Unshifted factors commute and form the supplied direct product.\n");
Print("The shifted third lift differs by a central element, and both generated lift subgroups contain that infinite-order central element.\n");
Print("PASS N5 arbitrary-lift obstruction\n");
QUIT;
